/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apartmani.sremac.hibernatesimpleapartmansmanage;

import com.apartmani.sremac.hibernatesimpleapartmansmanage.controller.ApartmanController;
import com.apartmani.sremac.hibernatesimpleapartmansmanage.controller.GostController;
import com.apartmani.sremac.hibernatesimpleapartmansmanage.controller.interfaces.IController;
import com.apartmani.sremac.hibernatesimpleapartmansmanage.models.Apartman;
import com.apartmani.sremac.hibernatesimpleapartmansmanage.models.Gost;
import com.toedter.calendar.JTextFieldDateEditor;
import java.lang.reflect.Array;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author radoj
 */
public class MainForm extends javax.swing.JFrame implements INotify{

    /**
     * Creates new form MainForm
     */
    IController<Gost> gostController;
    ApartmanController apartmanController;
    public MainForm() {
        initComponents();
        apartmanController=new ApartmanController();
      
        
     
        ApartmanCmb.setModel(new DefaultComboBoxModel<>(apartmanController.getApartmans()));
   
        gostController=new GostController(this);
       JTextFieldDateEditor editor = (JTextFieldDateEditor) DatumDo.getDateEditor();
        editor.setEditable(false);
               JTextFieldDateEditor editor1 = (JTextFieldDateEditor) DatumOd.getDateEditor();
        editor1.setEditable(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SearchButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        Od = new javax.swing.JLabel();
        PrezimeTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        P = new javax.swing.JLabel();
        ApartmanCmb = new javax.swing.JComboBox<>();
        ReserveButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Od1 = new javax.swing.JLabel();
        ImeTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PolCmb = new javax.swing.JComboBox<>();
        DatumOd = new com.toedter.calendar.JDateChooser();
        DatumDo = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(590, 400));
        setSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        SearchButton.setText("Pretrazi");
        SearchButton.setToolTipText("Pretrazi po apartmanu");

        jTextField1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(SearchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(387, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchButton)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 60));

        Od.setText("Do");
        getContentPane().add(Od, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        PrezimeTxt.setToolTipText("Pretrazi po apartmanu");
        getContentPane().add(PrezimeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 105, -1));

        jLabel2.setText("Prezime");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        P.setText("Pol");
        getContentPane().add(P, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        getContentPane().add(ApartmanCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 160, -1));

        ReserveButton.setText("Rezervisi");
        ReserveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReserveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ReserveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel3.setText("Apartman");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        Od1.setText("Od");
        getContentPane().add(Od1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 20, -1));

        ImeTxt.setToolTipText("Pretrazi po apartmanu");
        getContentPane().add(ImeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 105, -1));

        jLabel4.setText("Ime");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        PolCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Musko", "Zensko", "Drugo" }));
        getContentPane().add(PolCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, -1));

        DatumOd.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DatumOdPropertyChange(evt);
            }
        });
        getContentPane().add(DatumOd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 160, -1));
        getContentPane().add(DatumDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 160, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ReserveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReserveButtonActionPerformed
  
        
         if(DatumOd.getDate().before(DatumDo.getDate())){
             Apartman a=apartmanController.getApartman(ApartmanCmb.getSelectedItem().toString());
             if(a!=null){
                        Gost g=new Gost(ImeTxt.getText(),PrezimeTxt.getText(),PolCmb.getSelectedItem().toString(),DatumOd.getDate(),DatumDo.getDate(),a.getIdApartman());

      gostController.Reserve(g);
             }
             else{
                notify("Apartman nije dobro selektovan");
             }
 
         }
         else notify("Datum nije dobar");
    }//GEN-LAST:event_ReserveButtonActionPerformed

    private void DatumOdPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DatumOdPropertyChange
        if(DatumOd==null) return;
        DatumDo.setMinSelectableDate(DatumOd.getDate());
    }//GEN-LAST:event_DatumOdPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ApartmanCmb;
    private com.toedter.calendar.JDateChooser DatumDo;
    private com.toedter.calendar.JDateChooser DatumOd;
    private javax.swing.JTextField ImeTxt;
    private javax.swing.JLabel Od;
    private javax.swing.JLabel Od1;
    private javax.swing.JLabel P;
    private javax.swing.JComboBox<String> PolCmb;
    private javax.swing.JTextField PrezimeTxt;
    private javax.swing.JButton ReserveButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void notify(String message) {
       JOptionPane.showMessageDialog(rootPane, message);
    }
}
